sonar.organization=edbo
sonar.projectKey=edbo_ai_flow

sonar.sources=libs/*/src,services/*/src
sonar.tests=libs/*/tests,services/*/tests
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
sonar.python.version=3.13
